create table items (
	id bigint generated by default as identity,
	item_type varchar(31) not null,
	item_name varchar(255),
	author varchar(255),
	isbn varchar(255),
	director varchar(255),
	duration integer, primary key (id)
 );